
benchmark: aime24
# https://huggingface.co/datasets/HuggingFaceH4/aime_2024

# 30 problems, AIME I + II combined)

pre_prompt: |
  Solve the following math problem. Put your answer inside \boxed{}.

post_prompt: |
  Remember to put your answer inside \boxed{}.

num_rounds: 1
