
benchmark: matharena_apex
# https://huggingface.co/datasets/MathArena/apex_2025
# 12 difficult problems

pre_prompt: |
  Solve the following math problem. Put your answer inside \boxed{}.

post_prompt: |
  Remember to put your answer inside \boxed{}.

num_rounds: 1
