# model name and port come from .env (MODEL_N / PORT_N)

context_window: 32768

enable_thinking: true
thinking_budget: 15000
max_output_tokens: 10000

thinking_temp: 0.6
nonthinking_temp: 0.1
top_p: 0.95
top_k: 20
presence_penalty: 1.5
repetition_penalty: 1.0


# temp 0.0 for math 
