#!/usr/bin/env python3
"""
Helper for run_model_list.sh — generates temp model config files for one model entry.

Usage:
    python3 scripts/_generate_model_config.py <list_json> <idx> <project_root> <tmp_model_yaml> <tmp_env> [local_gguf_path]

Outputs shell variable assignments to stdout (to be sourced by the parent shell).
If local_gguf_path is provided, LOCAL_MODEL_N is set in the temp .env so the
llm service loads from the local file instead of downloading from HuggingFace.
"""
import json
import os
import re
import sys
from pathlib import Path


def main():
    args = sys.argv[1:]
    if len(args) < 5:
        print("Usage: _generate_model_config.py <list_json> <idx> <project_root> <tmp_yaml> <tmp_env> [local_gguf]", file=sys.stderr)
        sys.exit(1)

    list_json, idx_str, project_root, tmp_yaml, tmp_env = args[:5]
    local_gguf = args[5] if len(args) > 5 else ""
    slot_override = args[6] if len(args) > 6 else ""

    idx = int(idx_str)
    project_root = Path(project_root)

    with open(list_json) as f:
        d = json.load(f)

    models = d["models"]
    m = models[idx]
    slot = slot_override if slot_override else str(d.get("slot", 1))

    hf_repo = m.get("hf_repo", "")
    weights = m.get("weights", "")
    model_short = hf_repo.split("/")[-1] if hf_repo else f"model_{idx}"
    next_model = (
        models[idx + 1].get("hf_repo", "").split("/")[-1]
        if idx + 1 < len(models) else ""
    )

    # --- Generate temp model yaml ---
    base_yaml = project_root / "src" / "configs" / "model.yaml"
    base: dict = {}
    for line in base_yaml.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" in line:
            k, _, v = line.partition(":")
            v = v.strip()
            if v.lower() == "true":
                parsed: object = True
            elif v.lower() == "false":
                parsed = False
            else:
                try:
                    parsed = int(v)
                except ValueError:
                    try:
                        parsed = float(v)
                    except ValueError:
                        parsed = v
            base[k.strip()] = parsed

    skip_keys = {"hf_repo", "weights", "quant"}
    base.update({k: v for k, v in m.items() if k not in skip_keys})

    yaml_lines = ["# auto-generated by run_model_list.sh — do not edit"]
    for k, v in base.items():
        if isinstance(v, bool):
            yaml_lines.append(f"{k}: {str(v).lower()}")
        else:
            yaml_lines.append(f"{k}: {v}")
    Path(tmp_yaml).write_text("\n".join(yaml_lines) + "\n")

    # --- Generate temp .env ---
    env_file_rel = d.get("env_file", ".env")
    env_path = project_root / env_file_rel
    env_content = env_path.read_text()

    def _set_env(content: str, var: str, val: str) -> str:
        pattern = rf"^{re.escape(var)}\s*=.*"
        replacement = f"{var}={val}"
        if re.search(pattern, content, flags=re.MULTILINE):
            return re.sub(pattern, replacement, content, flags=re.MULTILINE)
        return content + f"\n{replacement}\n"

    # Always set MODEL_N to the HF repo (used as the model alias / API name)
    env_content = _set_env(env_content, f"MODEL_{slot}", hf_repo)

    if local_gguf:
        # Local GGUF: point LOCAL_MODEL_N to the container-visible path
        gguf_filename = os.path.basename(local_gguf)
        container_path = f"/app/models/{gguf_filename}"
        env_content = _set_env(env_content, f"LOCAL_MODEL_{slot}", container_path)
        # Clear WEIGHTS_N — not needed when using local file
        env_content = _set_env(env_content, f"WEIGHTS_{slot}", "")
    else:
        # HF GGUF: use normal hf-repo + hf-file flow
        env_content = _set_env(env_content, f"WEIGHTS_{slot}", weights)
        # Ensure LOCAL_MODEL_N is empty so docker-compose uses HF path
        env_content = _set_env(env_content, f"LOCAL_MODEL_{slot}", "")

    Path(tmp_env).write_text(env_content)

    # --- Output shell vars (sourced by run_model_list.sh) ---
    print(f"MODEL_SHORT_NAME={model_short!r}")
    print(f"HF_REPO={hf_repo!r}")
    print(f"WEIGHTS={weights!r}")
    print(f"NEXT_MODEL_NAME={next_model!r}")
    print(f"NEEDS_CONVERSION={'yes' if not weights else 'no'!r}")


if __name__ == "__main__":
    main()
